// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEPXweDV3lOqS2PPIjD1ltyPZ-pKE6joM',
    appId: '1:964805488289:web:17f976b6d607e1f3270ae0',
    messagingSenderId: '964805488289',
    projectId: 'cashshare-75637',
    authDomain: 'cashshare-75637.firebaseapp.com',
    storageBucket: 'cashshare-75637.firebasestorage.app',
    measurementId: 'G-R3CLB4M399',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ41Iaer7VPTQ_NMzK7qHC08oJatlajFc',
    appId: '1:964805488289:android:0499cb364d4f884f270ae0',
    messagingSenderId: '964805488289',
    projectId: 'cashshare-75637',
    storageBucket: 'cashshare-75637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSvN7MHQu4uOMIARMTViCMqjn8YGdt_6A',
    appId: '1:964805488289:ios:9803e2f39badfca1270ae0',
    messagingSenderId: '964805488289',
    projectId: 'cashshare-75637',
    storageBucket: 'cashshare-75637.firebasestorage.app',
    iosBundleId: 'com.example.ewallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSvN7MHQu4uOMIARMTViCMqjn8YGdt_6A',
    appId: '1:964805488289:ios:9803e2f39badfca1270ae0',
    messagingSenderId: '964805488289',
    projectId: 'cashshare-75637',
    storageBucket: 'cashshare-75637.firebasestorage.app',
    iosBundleId: 'com.example.ewallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEPXweDV3lOqS2PPIjD1ltyPZ-pKE6joM',
    appId: '1:964805488289:web:d50fbfe2bd3b76d1270ae0',
    messagingSenderId: '964805488289',
    projectId: 'cashshare-75637',
    authDomain: 'cashshare-75637.firebaseapp.com',
    storageBucket: 'cashshare-75637.firebasestorage.app',
    measurementId: 'G-8RD10HZY5X',
  );

}