// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvTqQtTcTHdJyejkLsN17sP4fg1KTf8Uc',
    appId: '1:711492263476:web:fb26cc3d42490a235b3461',
    messagingSenderId: '711492263476',
    projectId: 'darazreplica',
    authDomain: 'darazreplica.firebaseapp.com',
    storageBucket: 'darazreplica.firebasestorage.app',
    measurementId: 'G-73CQW1MJ4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLCQwGBIStvdleh994pGdyrohFt5I_cTw',
    appId: '1:711492263476:android:efec92f4cbb7991d5b3461',
    messagingSenderId: '711492263476',
    projectId: 'darazreplica',
    storageBucket: 'darazreplica.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwb_klfWXbewpkNWDfMkHqC5kiNTLs1UU',
    appId: '1:711492263476:ios:5608ab36679224345b3461',
    messagingSenderId: '711492263476',
    projectId: 'darazreplica',
    storageBucket: 'darazreplica.firebasestorage.app',
    iosBundleId: 'com.example.darazreplica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwb_klfWXbewpkNWDfMkHqC5kiNTLs1UU',
    appId: '1:711492263476:ios:5608ab36679224345b3461',
    messagingSenderId: '711492263476',
    projectId: 'darazreplica',
    storageBucket: 'darazreplica.firebasestorage.app',
    iosBundleId: 'com.example.darazreplica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvTqQtTcTHdJyejkLsN17sP4fg1KTf8Uc',
    appId: '1:711492263476:web:b462b84f6b0a385e5b3461',
    messagingSenderId: '711492263476',
    projectId: 'darazreplica',
    authDomain: 'darazreplica.firebaseapp.com',
    storageBucket: 'darazreplica.firebasestorage.app',
    measurementId: 'G-H9VL1X96EC',
  );

}